[versions]
# Android
android-gradle-plugin = "9.0.0"

minSdk = "24"
targetSdk = "36"
compileSdk = "36"
versionCode = "2"
versionName = "2.0.0"

# Kotlin
kotlin = "2.3.0"
core-ktx = "1.17.0"
appcompat = "1.7.1"
constraintlayout = "2.2.1"
material = "1.13.0"
timber = "5.0.1"
startup = "1.2.0"

# Test
junit = "4.13.2"
androidx-junit = "1.3.0"
espresso = "3.7.0"

# Tools
spotless = "8.2.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
androidx-startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "startup" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
androidx-test-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidx-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
